version: 2.1
orbs:
  codecov: codecov/codecov@1.0.5
jobs:
  test:
    working_directory: ~
    docker:
      - image: circleci/golang:1.12
    steps:
      - checkout
      - run:
          name: Run Tests
          command: go test ./... --coverprofile=coverage.txt
      - codecov/upload:
          file: coverage.txt
workflows:
  version: 2.1
  workflow:
    jobs:
      - test