version: 2.1
#orbs:
#  codecov: codecov/codecov@1.0.2
jobs:
  test:
    working_directory: ~
    docker:
      - image: golang:1.12-alpine
    steps:
      - checkout
      - run:
          name: Run Tests
          command: go test ./... --coverprofile=coverage.txt
#      - codecov/upload:
#          file: coverage.txt
workflows:
  version: 2.1
  workflow:
    jobs:
      - test